### ISSUE TITLE
AttributeError: 'ObjGeometry' object has no attribute 'linked_bone'

### ISSUE THREAD

**Issue by Heath123** [Robert-N7/abmatt#21]
When I import an OBJ using the GUI:
```
Converting /media/heath/Windows/Users/User/Desktop/mkwii-obj/portway.obj... 
No geometry found for Plane
Traceback (most recent call last):
  File "gui/converter.py", line 67, in run
  File "converters/convert_lib.py", line 188, in convert
  File "converters/convert_obj.py", line 35, in load_model
AttributeError: 'ObjGeometry' object has no attribute 'linked_bone'
```

**Comment by Robert-N7** [comment]
The statement "No geometry found for Plane" indicates that the obj file was not parsed correctly. Would you be willing to upload the obj file in question in a zip folder?

**Comment by Heath123** [comment]
Yes (the traceback seems to not cover everything and the second error is caused at https://github.com/Robert-N7/abmatt/blob/32fa5e42b7122bd51a0dfe206e70da6358e61e85/abmatt/converters/geometry.py#L247 I think)

**Comment by Heath123** [comment]
Do you need textures too?

**Comment by Heath123** [comment]
Uploading now

**Comment by Heath123** [comment]
https://drive.google.com/file/d/1Hhj7YrOa8T7dSeqpjNSVou9EdvNkWypl/view?usp=sharing

**Comment by Heath123** [comment]
OK, a ValueError causes that "'No geometry found" thing, maybe I can see why it's being thrown?

**Comment by Heath123** [comment]
`ValueError: cannot reshape array of size 12 into shape (3,3)`

**Comment by Heath123** [comment]
Relevant (I think) part of the OBJ:
```obj
o Plane
v 1.468444 0.051206 0.566331
v 1.604718 0.051206 0.566331
v 1.468444 0.113100 0.007058
v 1.604718 0.113100 0.007058
vt 0.000000 0.000000
vt 1.000000 0.000000
vt 1.000000 1.000000
vt 0.000000 1.000000
vn 0.0000 0.9939 0.1100
```

**Comment by Heath123** [comment]
And the error is thrown at
https://github.com/Robert-N7/abmatt/blob/32fa5e42b7122bd51a0dfe206e70da6358e61e85/abmatt/converters/obj.py#L90

**Comment by Heath123** [comment]
This is the array it can't reshape:
```python
[[[2453, 3357, 457], [2454, 3358, 457], [2456, 3359, 457], [2455, 3360, 457]]]
```

**Comment by Heath123** [comment]
I don't have much experience with this, but looks like it's a quad, not a triangle?

**Comment by Heath123** [comment]
I'll see if this works:
![image](https://user-images.githubusercontent.com/13787163/107883214-87cf2d80-6ee5-11eb-96bd-ada9724847c0.png)

**Comment by Heath123** [comment]
Looks like that split it into two triangles:
```obj
o Plane
v 1.468444 0.051206 0.566331
v 1.604718 0.051206 0.566331
v 1.604718 0.113100 0.007058
v 1.468444 0.113100 0.007058
vt 1.000000 0.000000
vt 0.000000 1.000000
vt 0.000000 0.000000
vt 1.000000 1.000000
vn 0.0000 0.9939 0.1100
usemtl Material.005
s 1
f 2452/3357/507 2454/3358/507 2451/3359/507
f 2452/3357/507 2453/3360/507 2454/3358/507
```

**Comment by Heath123** [comment]
That fixed the first error, but not the second

**Comment by Heath123** [comment]
I commented out
https://github.com/Robert-N7/abmatt/blob/32fa5e42b7122bd51a0dfe206e70da6358e61e85/abmatt/converters/geometry.py#L247
which seems to fix it, but now I get `AttributeError: 'ObjGeometry' object has no attribute 'colors'`...
Maybe I should add checks that the values exist and PR that? Or do they need to exist for the check to work?

**Comment by Heath123** [comment]
Also commenting
https://github.com/Robert-N7/abmatt/blob/32fa5e42b7122bd51a0dfe206e70da6358e61e85/abmatt/converters/geometry.py#L249
seems to fixes it, I might PR a proper check (am I writing too many comments?)

**Comment by Robert-N7** [comment]
The issue was it was trying to combine an ObjGeometry object, instead of a generic geometry object.
`material_geometry_map[mat].combine(geo)`

**Comment by Heath123** [comment]
Oh, can you fix that?

**Comment by Heath123** [comment]
Oh wait, you just change `geometry` to `geo`

**Comment by Heath123** [comment]
Thank you
Maybe you could also make it triangulate the faces, or at least fail with a nicer error ("Error: Please triangulate your model before importing it!" or something)

**Comment by Robert-N7** [comment]
I'll add a nicer error message in as well
