### ISSUE TITLE
Model looks wrong after being reimported

### ISSUE THREAD

**Issue by Heath123** [Robert-N7/abmatt#28]
After exporting a DAE file from Luigi Circuit and reimporting it to the same file using the Replace function, it looks like this:
![image](https://user-images.githubusercontent.com/13787163/114435982-b94e3780-9bbc-11eb-83e3-0fd084acf131.png)
As far I can tell everything is partially transparent so the sky shows through
Also shadows look too dark

**Comment by Robert-N7** [comment]
Interesting, I'll look into it

**Comment by Robert-N7** [comment]
I've gotten a handle on the blue fog and shadows. The blue fog was caused by an incorrect bp mask address being packed for the material graphics. There seemed to be another bug as well with unpacking the color register which I believe was the cause of the darker shadows.

**Comment by Heath123** [comment]
Yay, thank you
