### ISSUE TITLE
Blank model in game

### ISSUE THREAD

**Issue by Heath123** [Robert-N7/abmatt#35]
When imported into the game through replacement or importing from scratch, [this model](https://github.com/Robert-N7/abmatt/files/6313254/model.zip) gives a blank void:
![image](https://user-images.githubusercontent.com/13787163/114768217-7b8a1400-9d60-11eb-8f4d-9d973db11ae6.png)

**Comment by Robert-N7** [comment]
This is an issue with the way blender exports its dae files. It ends up importing things twice, causing issues in game. If I import in 3ds max it also duplicates things. I'll see if I can work out a fix.

**Comment by Heath123** [comment]
It still looks blank for me?

**Comment by Heath123** [comment]
I think the problem might be Blender not exporting the textures properly

**Comment by Heath123** [comment]
Wait, no, I found the issue, it's that the units are like this:
`<unit name="kilometer" meter="1000"/>`
But abmatt doesn't read that so it's 1000 times too small

**Comment by Robert-N7** [comment]
It does detect the file units [https://github.com/Robert-N7/abmatt/blob/2346eedcce541ce250b5b3bdc29fd1a799858038/abmatt/converters/dae.py#L465](url)
It works for me both by importing or replacing. I haven't only tested on windows 10 though.

**Comment by Heath123** [comment]
Oh... I can upload the file that doesn't work later
