### ISSUE TITLE
Object doesn't show up when not in the right vertex group/armature

### ISSUE THREAD

**Issue by Heath123** [Robert-N7/abmatt#39]
Not sure if this is a bug or a feature request but wouldn't it make sense for new objects to be added the right thing so they show up in game automatically?

**Comment by Robert-N7** [comment]
I think you mean the bones, which would make sense for objects that should only be bound to one bone, however there are objects in Mario kart wii bound to multiple different bones... Please correct me if I'm not understanding correctly.

**Comment by Heath123** [comment]
Maybe have a default bone option?

**Comment by Heath123** [comment]
Or is that type of processing something that should be done by a separate tool?

**Comment by Robert-N7** [comment]
I'm adding a single-bone option for converting... coming soon!

**Comment by Robert-N7** [comment]
I've got the single-bone option working, I believe this issue should be fixed once I merge the PR but can you verify?
