### ISSUE TITLE
Feature request: Exporting object data without having to do a replacement

### ISSUE THREAD

**Issue by Heath123** [Robert-N7/abmatt#40]
If material data can't be included in the DAE/OBJ, can it at least be written to a text file or something, so you don't have to do the Replace thing and you can combine materials from different tracks/edit materials?

**Comment by Robert-N7** [comment]
That is what the material library/scene material library is for, you can drag and drop materials onto the polygons... and if you double click on the material you can edit it.

**Comment by Heath123** [comment]
I'm trying to make a Blender plugin, so it would be nice to be able to import the properties into Blender and edit them there

**Comment by Robert-N7** [comment]
That makes more sense to me now, yes we could definitely work something out. I worry that including the data in the dae or obj would create errors in 3rd-party tools importing them, so a separate text file may be best.

**Comment by Heath123** [comment]
From what I understand Blender Python scripts let you add custom properties to things like materials so I was thinking that it could import the data into that

**Comment by Heath123** [comment]
This is what I'm making:
https://youtu.be/evf61IebDd4

**Comment by Robert-N7** [comment]
That looks super cool, I'm working on being able to dump the material data into a json file. Will that work for you?

**Comment by Heath123** [comment]
Sounds good, thank you

**Comment by Heath123** [comment]
As long as I can match up the imported material with the properties and export it again, and the structure of JSON isn't a complicated nested thing that I can't convert to a UI that will be perfect

**Comment by Robert-N7** [comment]
Ahhh, but the nature of brres materials is complex. There is multiple layers to each material, shader, shader stages, light channels, colors, matrices, animations, you get the picture. It would be easy enough to reload using my python packages... But I'm not sure about displaying every setting.

**Comment by Heath123** [comment]
Ah, OK, in the worst case I can make a JSON editor so it's fine

**Comment by Heath123** [comment]
Thank you! I'll try to make this work when the few final issues with model exporting are solved

**Comment by Heath123** [comment]
Seems to work perfectly so far, thank you
