### ISSUE TITLE
Textures broken?

### ISSUE THREAD

**Issue by Heath123** [Robert-N7/abmatt#43]
[This model](https://github.com/Robert-N7/abmatt/files/6331077/model.zip) looks like this in Blender:
![image](https://user-images.githubusercontent.com/13787163/115143043-e0818a80-a03c-11eb-8e34-f1c549517511.png)
but like this in-game (using Free Look for a clearer view):
![image](https://user-images.githubusercontent.com/13787163/115143031-ce075100-a03c-11eb-8f29-1c644b9bc7c9.png)
It changes as you get closer/further away so it might be to do with mipmaps or something

**Comment by Heath123** [comment]
(I'm using random pictures from my PC to test which is why I have a track with a random image of a dog looking at a computer)

**Comment by Robert-N7** [comment]
I was unable to reproduce this, is it with the latest changes? Because I recently updated to fix a bug where it did not resize the image to a power of two.

**Comment by Heath123** [comment]
I'll try to get more information about when it happens tomorrow

**Comment by Heath123** [comment]
Still happens for me

**Comment by Heath123** [comment]
BRRES:
[course_model.zip](https://github.com/Robert-N7/abmatt/files/6345301/course_model.zip)

**Comment by Heath123** [comment]
It looks fine in a BRRES viewer, but not in game

**Comment by Heath123** [comment]
Resizing orl.png to 1024x1024 fixes it, my guess is that the game expects a square aspect ratio and if not it treats it as a mipmap like this:
![image](https://mlhr8q6s8c91.i.optimole.com/VVLFqVU-fxiu5NwV/w:768/h:512/q:90/https://www.imaginationtech.com/wp-content/uploads/2019/08/example_mipmap_chain-1.png)
That's a guess though, I'll investigate a bit more

**Comment by Heath123** [comment]
Oh, I noticed that it only resizes the smk image and not orl in the output:
```
TEX0 smk 1024x1093 (CMPR) not a power of 2
Replaced tex0 smk
(FIXED): Resize to 1024x1024
```
