### ISSUE TITLE
Textures not URL decoded?

### ISSUE THREAD

**Issue by Heath123** [Robert-N7/abmatt#46]
`WARN: Failed to find image smk%20(copy).png`
The image is called `smk (copy).png` so it seems like it needs to URL decode?

**Comment by Robert-N7** [comment]
Ahhh, the bane of using spaces in file paths. I also played around and it turns out if you export with a space in your filename it will wreck 3ds max when it tries to import / export. I'll add a check for decoding it as a url, but my recommendation is **don't use spaces in your file names.**

**Comment by Heath123** [comment]
It is easy enough to rename the file, but I'm hoping to help make this more robust by reporting all the bugs I find

**Comment by Heath123** [comment]
There are still issues with textures with spaces
