### ISSUE TITLE
Model in the wrong position after #49

### ISSUE THREAD

**Issue by Heath123** [Robert-N7/abmatt#50]
#49 fixes #48, but also causes the model to be in the wrong place
Before:
![image](https://user-images.githubusercontent.com/13787163/115584070-63ffdd80-a2c2-11eb-85f4-3bfc72a3f1e1.png)
After:
![image](https://user-images.githubusercontent.com/13787163/115584224-872a8d00-a2c2-11eb-9fbf-1aff8805bd1d.png)

**Comment by Heath123** [comment]
This doesn't happen when removing the armature

**Comment by Robert-N7** [comment]
Can you upload the file so I can verify the fix? I believe I've gotten multiple bones working with 3ds dae files but I would like to check with blender.

**Comment by Heath123** [comment]
It should happen on the one linked in #43
