### ISSUE TITLE
Models crashing on console, but not Dolphin

### ISSUE THREAD

**Issue by Heath123** [Robert-N7/abmatt#55]
I can upload a video if needed, I see a black screen and hear the intro music but then nothing else
[files.zip](https://github.com/Robert-N7/abmatt/files/6367303/files.zip)
I've confirmed that this is caused by the model as using one from a normal track works

**Comment by Heath123** [comment]
On http://wiki.tockdom.com/wiki/Common_Crash_Causes under BRRES it says:
> Before replacing a material with BrawlBox, you should remove all its texture references (unnecessary if you are playing on Dolphin, but required on a real Wii).
I'm not really sure what that means in this context but could that be why, as it's something that's only needed on the real Wii?

**Comment by Robert-N7** [comment]
I'll have to look into the file, if it's because of a missing reference then a warning would show up when saving.

**Comment by Heath123** [comment]
> Converting /tmp/course.dae... 
	... finished in 0.78 secs
Cube UV Channel 0 is not used by material.
Shader Material-material: Stage 0 no such layer
(FIXED): Remove stage
Shader Material-material: has no stages!
(FIXED): Set solid color (0, 0, 0, 0)
TEX0 smk 1024x1093 (CMPR) not a power of 2
Replaced tex0 smk
(FIXED): Resize to 1024x1024
  - create octree: rshift=16, n_bcube=32, cube_size=512..1048576, blow=400, max_tri=30, max_depth=10, fast=0
CREATE /home/heath/mk-plugin/test-track/ -> YAZ0.U8:/home/heath/mk-plugin/disc/DATA/files/Race/Course/beginner_course.szs

**Comment by Robert-N7** [comment]
It could be, but it uses a default color instead for the material (black) so I'm surprised if that causes the crash

**Comment by Heath123** [comment]
It appears white for me in Dolphin for some reason

**Comment by Heath123** [comment]
No, that wasn't it

**Comment by Heath123** [comment]
Anything else I can do debug?

**Comment by Robert-N7** [comment]
Based on some tests, I found that  black screens occurs when converting models, not only with the v0.9.3 but all previous versions as well. Curiously, the black screen doesn't happen when abmatt simply loads and saves a brres file. When looking through the model, nothing immediately appears to be out of order, still digging...

**Comment by Robert-N7** [comment]
I believe I have found the issue, for some reason the data length of polygons must include the extra alignment padding on the Wii. I'll create a pull request once I've verified the fix.

**Comment by Heath123** [comment]
Yay, thank you! Hopefully I can test this soon

**Comment by Heath123** [comment]
![IMG_20210428_170918810](https://user-images.githubusercontent.com/13787163/116436776-a5553780-a844-11eb-84a7-f37ece193325.jpg)
It works now, thank you!
