### ISSUE TITLE
Broken textures

### ISSUE THREAD

**Issue by Heath123** [Robert-N7/abmatt#72]
[model.zip](https://github.com/Robert-N7/abmatt/files/6987315/model.zip)
Blender:
![image](https://user-images.githubusercontent.com/13787163/129462939-fd65970a-1ad6-4d9f-86b0-aab5775ec5f9.png)
In game:
![image](https://user-images.githubusercontent.com/13787163/129462972-f37b7f68-f111-461d-b0e0-dc9a8decf584.png)

**Comment by Heath123** [comment]
If you get very close using Free Look you can see this
![image](https://user-images.githubusercontent.com/13787163/129483806-be7232ce-e9ac-4bfe-80b9-228ee0d71aa8.png)

**Comment by Heath123** [comment]
Converting it back to DAE and importing it, the UV map is way too big (as expected):
https://user-images.githubusercontent.com/13787163/129484517-49ad95f7-8ea9-404a-80c1-3372526d1b3d.mp4

**Comment by Heath123** [comment]
Scaling it by 0.0000305 gets it back to the right position, and 1 / 0.0000305 = 32786.8852459 which is very close to 2 ^ 15 or 32768

**Comment by Heath123** [comment]
So it's 65536 times too big

**Comment by Heath123** [comment]
Oh: 
`ERROR: Geometry Cylinder#0 divisor 16 out of range`
![image](https://user-images.githubusercontent.com/13787163/129485167-c49c06d3-48b6-4ea9-b83d-073d97b463b6.png)
That _definitely_ seems like the problems

**Comment by Heath123** [comment]
```
if self.divisor >= 16:
    AutoFix.error('Geometry {} divisor {} out of range'.format(self.name, self.divisor))
    self.divisor = 0
    result = True
```
So you set divisor to 0, which would make everything 65536 times bigger than it would be
Removing the check fixes it for me, why does it need to be there? (also the warning says geometry but `point.py` is also used for texture ccordinates)

**Comment by Robert-N7** [comment]
I believe this was an issue that I fixed in my development branch, still working to get it passing all checks though... There was an off by one bug detecting the precision needed for texture coordinates, which resulted in using the 16-bit format with a divisor of 16… as you see that fires the check that resets it to 0. You may think it's not necessary but in ctools models it's very common to have invalid divisor values. I'm not sure how it fixed it in your case, as shifting a 16 bit integer 16 times results in... Well nothing

**Comment by Heath123** [comment]
> I believe this was an issue that I fixed in my development branch, still working to get it passing all checks though... There was an off by one bug detecting the precision needed for texture coordinates, which resulted in using the 16-bit format with a divisor of 16… as you see that fires the check that resets it to 0. You may think it's not necessary but in ctools models it's very common to have invalid divisor values. I'm not sure how it fixed it in your case, as shifting a 16 bit integer 16 times results in... Well nothing

If you want to work out why I attached a model that should reproduce it in the issue

**Comment by Heath123** [comment]
> You may think it's not necessary

I know it's there for a reason, I just mean I need to know what it does to fix it properly
